### ISSUE TITLE
Switch to GraphQL

### ISSUE THREAD

**Issue by f0lg0** [fb-co/devsbunker#3]
# From REST to GraphQL

## Source

[youtube](https://www.youtube.com/watch?v=H8YnVk2vhzg&list=PLizg5PoGqZIn2rJUG1pbDp0ThOAOj0W2L&index=108)

[src](https://github.com/steveluscher/zero-to-graphql)

## Requirements

npm packages:

* ``graphql``
* ``express-graphql``

## Todo

- [x] Define the needed graphql schemas

- [x] Define GraphQLObjectTypes

  - [x] look at stuff like GraphQLList

- [x] While resolving the schema we can return promises

  - [x] this means that we can call our existing REST API

    - [x] ```javascript
      fetch(`${BASE_URL`/posts/${args.id}/)
      ```

- [ ] Use  `data loaders` to avoid overloading the API

## Warning

``DataLoader`` is a tool to avoid huge nested queries like

```
query {
	user {
		friends {
			friends {
				friends {
					...
				}
			}
		}
	}
}
```

That will overload the REST API.

## Example

```javascript
import DataLoader from 'dataloader';

import express from 'express';
import fetch from 'node-fetch';
import graphqlHTTP from 'express-graphql';
import schema from './schema';

const BASE_URL = 'http://localhost:8000';

function getJSONFromRelativeURL(relativeURL) {
  return fetch(`${BASE_URL}${relativeURL}`)
    .then(res => res.json());
}

function getPeople() {
  return getJSONFromRelativeURL('/people/')
    .then(json => json.people);
}

function getPerson(id) {
  return getPersonByURL(`/people/${id}/`);
}

function getPersonByURL(relativeURL) {
  return getJSONFromRelativeURL(relativeURL)
    .then(json => json.person);
}

const app = express();

app.use(graphqlHTTP(req => {
  const cacheMap = new Map();
  const peopleLoader =
    new DataLoader(keys => Promise.all(keys.map(getPeople)), {cacheMap});
  const personLoader =
    new DataLoader(keys => Promise.all(keys.map(getPerson)), {
      cacheKeyFn: key => `/people/${key}/`,
      cacheMap,
    });
  const personByURLLoader =
    new DataLoader(keys => Promise.all(keys.map(getPersonByURL)), {cacheMap});
  personLoader.loadAll = peopleLoader.load.bind(peopleLoader, '__all__');
  personLoader.loadByURL = personByURLLoader.load.bind(personByURLLoader);
  personLoader.loadManyByURL =
    personByURLLoader.loadMany.bind(personByURLLoader);
  const loaders = {person: personLoader};
  return {
    context: {loaders},
    graphiql: true,
    schema,
  };
}));

app.listen(
  5000,
  () => console.log('GraphQL Server running at http://localhost:5000')
);
```

Schema

```javascript
import fetch from 'node-fetch';
import {
  GraphQLID,
  GraphQLList,
  GraphQLNonNull,
  GraphQLObjectType,
  GraphQLSchema,
  GraphQLString,
} from 'graphql';
import {
  fromGlobalId,
  globalIdField,
  nodeDefinitions,
} from 'graphql-relay';

const {
  nodeField,
  nodeInterface,
} = nodeDefinitions(
  // A method that maps from a global id to an object
  (globalId, {loaders}) => {
    const {id, type} = fromGlobalId(globalId);
    if (type === 'Person') {
      return loaders.person.load(id);
    }
  },
  // A method that maps from an object to a type
  (obj) => {
    if (obj.hasOwnProperty('username')) {
      return PersonType;
    }
  }
);

const PersonType = new GraphQLObjectType({
  name: 'Person',
  description: 'Somebody that you used to know',
  fields: () => ({
    id: globalIdField('Person'),
    firstName: {
      type: GraphQLString,
      description: 'What you yell at me',
      resolve: obj => obj.first_name,
    },
    lastName: {
      type: GraphQLString,
      description: 'What you yell at me when I\'ve been bad',
      resolve: obj => obj.last_name,
    },
    fullName: {
      type: GraphQLString,
      description: 'A name sandwich',
      resolve: obj => `${obj.first_name} ${obj.last_name}`,
    },
    email: {
      type: GraphQLString,
      description: 'Where to send junk mail',
    },
    username: {
      type: GraphQLString,
      description: 'Log in as this',
    },
    friends: {
      type: new GraphQLList(PersonType),
      description: 'People who lent you money',
      resolve: (obj, args, {loaders}) =>
        loaders.person.loadManyByURL(obj.friends),
    },
  }),
  interfaces: [nodeInterface],
});

const QueryType = new GraphQLObjectType({
  name: 'Query',
  description: 'The root of all... queries',
  fields: () => ({
    allPeople: {
      type: new GraphQLList(PersonType),
      description: 'Everyone, everywhere',
      resolve: (root, args, {loaders}) => loaders.person.loadAll(),
    },
    node: nodeField,
    person: {
      type: PersonType,
      args: {
        id: {type: new GraphQLNonNull(GraphQLID)},
      },
      resolve: (root, args, {loaders}) => loaders.person.load(args.id),
    },
  }),
});

export default new GraphQLSchema({
  query: QueryType,
});
```
